language: objective-c  #1
osx_image: xcode8.2    #2
xcode_sdk: iphonesimulator10.2 #3
xcode_project: BLE_Demo.xcodeproj #4
xcode_scheme: BLE_Demo #5
script: xcodebuild -project BLE_Demo.xcodeproj -target BLE_Demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
